### 课程查询api
POST {{content_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "",
  "courseName": "",
  "publishStatus": "203001"
}

### 查询数据字典api
GET {{system_host}}/system/dictionary/all
Content-Type: application/json

### 查询课程全部类型
GET {{content_host}}/content/course-category/tree-nodes
Content-Type: application/json

### 添加课程信息
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "description": "测试一下而已",
  "grade": "204001",
  "mt": "1-9",
  "name": "x",
  "originalPrice": 19998,
  "phone": "114514",
  "pic": "",
  "price": 18888,
  "qq": "112344556",
  "st": "1-9-2",
  "tags": "teach",
  "teachmode": "200002",
  "users": "",
  "validDays": 365,
  "wechat": "pp444"
}

### 查询某个课程的课程计划
GET {{content_host}}/content/teachplan/117/tree-nodes
Content-Type: application/json

### 提交课程审核的接口
POST {{content_host}}/content/courseaudit/commit/118
Content-Type: application/json

### 课程发布
POST {{content_host}}/content/coursepublish/118
Content-Type: application/json

### 课程查询
GET {{content_host}}/content/course/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib3MiXSwidXNlcl9uYW1lIjoie1wiY29tcGFueUlkXCI6XCIxMjMyMTQxNDI1XCIsXCJjcmVhdGVUaW1lXCI6XCIyMDIyLTA5LTI4VDA4OjMyOjAzXCIsXCJpZFwiOlwiNTJcIixcIm5hbWVcIjpcIk3ogIHluIhcIixcInNleFwiOlwiMVwiLFwic3RhdHVzXCI6XCJcIixcInVzZXJuYW1lXCI6XCJ0MVwiLFwidXR5cGVcIjpcIjEwMTAwMlwifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2Nzg5NzY3MzksImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiODAyZjNmYTItZmRkZS00NTA1LTk5ZmItNjlhZDIwMGUwYzI4IiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.sjcE5e6agvhDZEG74z2J5pxtCJYCyfAIjk2BwBRWvSw

### 通过网关查询课程
GET {{gateway_host}}/content/course/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib3MiXSwidXNlcl9uYW1lIjoiemhhbmdzYW4iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjc4OTY1NDAyLCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiIxMTI5YjliYi04ZTA4LTQ2NmYtYmQ4My0wNjViMDQwZDk1OWEiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.IvjNWZuam4BkIeTz1HJzA_u-6eZJofSvFCLCJeoDEQU