### 课程查询api
POST {{content_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "",
  "courseName": "",
  "publishStatus": "203001"
}

### 查询数据字典api
GET {{system_host}}/system/dictionary/all
Content-Type: application/json

### 查询课程全部类型
GET {{content_host}}/content/course-category/tree-nodes
Content-Type: application/json